spring:
  data:
    mongodb:
      uri: mongodb://ISIS2304B30202320:BejTkUbsHbBH@157.253.236.88:8087/ISIS2304B30202320
      database: ISIS2304B30202320

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
