spring:
  data:
    mongodb:
      uri: CAMBIAR_ESTO_POR_LA_URI_DE_CONEXION
      database: CAMBIAR_ESTO_POR_EL_NAME_DE_LA_BASE_DE_DATOS_A_USAR

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
